### PR TITLE
Added storing of chat history to Cosmos DB

### PR DESCRIPTION
**Pull request by lyndonlim27**
### Deployment files
Updated `azure.yaml` ,`main.bicep`, `main.parameters.json` and `cosmos.bicep` to accomodate for feedback and chat history container/database id.

### Backend code
- Updated response_handler.py to send chat history to azure cosmos db
    - Chat history will be appended if session id is identical
- Updated app.py to pull the new env variables (feedback and chat history container/database id)
- Added ChatHistory pydantic model to validate parameters before storing in CosmosDB
- Added a try catch when closing websocket 
- Fixed setting of session id in cookies (Previously the session id changes if the server is restarted)

### Backend test
- Added a simple terminal UI for backend testing

### CODE REVIEW

**Comment by lyndonlim27** [comment]
Let me make some name changes first

**Comment by lyndonlim27** [comment]
Okay updated!

**Review by Wilsven — APPROVED** [review]
@lyndonlim27 Do you need the latest version to be deployed?

**Comment by lyndonlim27** [comment]
> @lyndonlim27 Do you need the latest version to be deployed?

Yes but let me merge the frontend changes (they just made a pr)and test it first before deploying.

**Pull request merged**
